---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cars":
    post:
      summary: Creates a car
      tags:
      - Car
      parameters: []
      responses:
        '201':
          description: Car created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                model:
                  type: string
                release_year:
                  type: integer
                color:
                  type: string
                transmission:
                  type: string
                price:
                  type: integer
                seats:
                  type: integer
                wheel_drive:
                  type: string
                image_link:
                  type: string
                user_id:
                  type: integer
              required:
              - id
              - brand
              - model
              - release_year
              - color
              - transmission
              - seats
              - wheel_drive
              - price
              - user_id
          application/xml:
            schema:
              type: object
              properties:
                id:
                  type: integer
                model:
                  type: string
                release_year:
                  type: integer
                color:
                  type: string
                transmission:
                  type: string
                price:
                  type: integer
                seats:
                  type: integer
                wheel_drive:
                  type: string
                image_link:
                  type: string
                user_id:
                  type: integer
              required:
              - id
              - brand
              - model
              - release_year
              - color
              - transmission
              - seats
              - wheel_drive
              - price
              - user_id
  "/api/v1/cars/{id}":
    get:
      summary: Retrieves a car
      tags:
      - Cars
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: name found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  brand:
                    type: string
                  model:
                    type: string
                  release_year:
                    type: integer
                  color:
                    type: string
                  transmission:
                    type: string
                  price:
                    type: integer
                  seats:
                    type: integer
                  wheel_drive:
                    type: string
                  image_link:
                    type: string
                  user_id:
                    type: integer
                required:
                - id
                - brand
                - model
                - release_year
                - color
                - transmission
                - seats
                - wheel_drive
                - price
                - user_id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  brand:
                    type: string
                  model:
                    type: string
                  release_year:
                    type: integer
                  color:
                    type: string
                  transmission:
                    type: string
                  price:
                    type: integer
                  seats:
                    type: integer
                  wheel_drive:
                    type: string
                  image_link:
                    type: string
                  user_id:
                    type: integer
                required:
                - id
                - brand
                - model
                - release_year
                - color
                - transmission
                - seats
                - wheel_drive
                - price
                - user_id
        '404':
          description: car not found
    delete:
      summary: Deletes a car
      tags:
      - Cars
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: event deleted
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
